import os
from pathlib import Path
from snakemake.utils import min_version, validate

min_version("8.20.1")

WORKFLOW_DIR = Path(workflow.basedir).resolve()
validate(config, str(WORKFLOW_DIR / "schemas" / "config.schema.yaml"))

include: os.path.join("rules", "common.smk")

include: os.path.join("rules", "audit.smk")
include: os.path.join("rules", "mixscape.smk")
include: os.path.join("rules", "mixscale.smk")
include: os.path.join("rules", "ps.smk")
include: os.path.join("rules", "comparison.smk")

localrules: all

rule all:
    input:
        all_targets()
